---
- name:  Display Cisco info
  hosts: cisco
  gather_facts: no
  
  tasks:

    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          This is Nikki's super cool login banner
          The Hostname of the switch is: {{ inventory_hostname }}
        state: present