---
- name:  Set ospf
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Override provided OSPF Interfaces configuration
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: GigabitEthernet2
            address_family:
              - afi: ipv4
                process:
                  id: 10
                  area_id: 0
                adjacency: true
                cost:
                  interface_cost: 30
                priority: 40
                ttl_security:
                  hops: 50
        state: overridden